### ISSUE TITLE
Is it possible to run SKSV on bam files?

### ISSUE THREAD

**Issue by LYC-vio** [ydLiu-HIT/SKSV#1]
Hi,
 
I'm trying to test your tool on several datasets, and it runs smoothly on the fastq inputs.My only concern is that, is there anyway to run SKSV on some already aligned results? Like bam files from NGMLR or minimap2.

Thank you.

您好，我最近正尝试在一些Longread数据上测试您的SKSV软件。依照您Readme中的说明，我成功在fastq文件上运行了SKSV，不过对于一些数据，我可能希望能跳过SKSV的align步骤，而使用我已有的NGMLR和minimap2 align出的bam文件作为sv call的输入。SKSV有可能在bam文件上完成SV call的操作吗？您的文章中提到SVSK在call步骤中采用了cuteSV的部分思想，据我了解cuteSV可以接受bam文件输入，但是似乎SKSV的call步骤输入是svseg文件。svseg和bam可以互相转换吗？

非常感谢

**Comment by ydLiu-HIT** [comment]
Hi Yichen,
Sorry to tell you that SKSV now only supports raw fastq as input to call SV. The calling method is similar to cuteSV developed by Tao Jiang. If I add an interface to support BAM as input, the performance may be similar to cuteSV, thus you can take the performance of cuteSV as a reference to benchmark SKSV.
